// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBf3-R6y3MrPjhczkruE1ZOusnuTA_F44',
    appId: '1:864300918868:web:27cd9ca96eb474b25025c1',
    messagingSenderId: '864300918868',
    projectId: 'syntese-72031',
    authDomain: 'syntese-72031.firebaseapp.com',
    storageBucket: 'syntese-72031.firebasestorage.app',
    measurementId: 'G-BHY6G9SW2B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjd5TlV6Eh7w_tM_jq5l3MZoIeYjCZ9b0',
    appId: '1:864300918868:ios:c1f305c4f9f3dc885025c1',
    messagingSenderId: '864300918868',
    projectId: 'syntese-72031',
    storageBucket: 'syntese-72031.firebasestorage.app',
    iosBundleId: 'com.example.projetSyn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjd5TlV6Eh7w_tM_jq5l3MZoIeYjCZ9b0',
    appId: '1:864300918868:ios:c1f305c4f9f3dc885025c1',
    messagingSenderId: '864300918868',
    projectId: 'syntese-72031',
    storageBucket: 'syntese-72031.firebasestorage.app',
    iosBundleId: 'com.example.projetSyn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBf3-R6y3MrPjhczkruE1ZOusnuTA_F44',
    appId: '1:864300918868:web:a44b1a8f0ed448da5025c1',
    messagingSenderId: '864300918868',
    projectId: 'syntese-72031',
    authDomain: 'syntese-72031.firebaseapp.com',
    storageBucket: 'syntese-72031.firebasestorage.app',
    measurementId: 'G-7D2JJWPNME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ObauXyJ6R0wi3KQzHWfpCdcBdSKx7FE',
    appId: '1:864300918868:android:e28d8f5a77b210305025c1',
    messagingSenderId: '864300918868',
    projectId: 'syntese-72031',
    storageBucket: 'syntese-72031.firebasestorage.app',
  );

}